[Interface]
PrivateKey = Reading package lists...
Building dependency tree...
Reading state information...
wireguard-tools is already the newest version (1.0.20210914-3).
Solving dependencies...
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 0
aOePP7yYNL3oeKB47VwlCjH5xY+FkX3EIHqag+wjt3g=
ListenPort = 51820

[Peer]
PublicKey = 
AllowedIPs = 0.0.0.0/0
Endpoint = 1.1.1.1:51820
